"""create_campaigns_and_assets

Revision ID: 6d964d031095
Revises: 2f_audit_notifications_apikeys
Create Date: 2026-07-31 12:28:36.599784

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "6d964d031095"
down_revision: Union[str, Sequence[str], None] = "2f_audit_notifications_apikeys"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "assets",
        sa.Column("uploaded_by", sa.UUID(), nullable=True),
        sa.Column("file_name", sa.String(), nullable=False),
        sa.Column("original_file_name", sa.String(), nullable=False),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("asset_type", sa.String(), nullable=False),
        sa.Column("mime_type", sa.String(), nullable=False),
        sa.Column("file_size", sa.BigInteger(), nullable=False),
        sa.Column("storage_provider", sa.String(), nullable=False),
        sa.Column("storage_key", sa.String(), nullable=False),
        sa.Column("public_url", sa.String(), nullable=True),
        sa.Column("thumbnail_url", sa.String(), nullable=True),
        sa.Column("width", sa.Integer(), nullable=True),
        sa.Column("height", sa.Integer(), nullable=True),
        sa.Column("duration", sa.Integer(), nullable=True),
        sa.Column("checksum", sa.String(), nullable=False),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("folder", sa.String(), nullable=True),
        sa.Column("tags", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_assets_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_assets_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["uploaded_by"],
            ["users.id"],
            name=op.f("fk_assets_uploaded_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_assets_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_assets")),
        sa.UniqueConstraint("storage_key", name=op.f("uq_assets_storage_key")),
    )
    op.create_index("ix_assets_asset_type", "assets", ["asset_type"], unique=False)
    op.create_index("ix_assets_checksum", "assets", ["checksum"], unique=False)
    op.create_index("ix_assets_created_at", "assets", ["created_at"], unique=False)
    op.create_index(
        op.f("ix_assets_deleted_at"), "assets", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_assets_id"), "assets", ["id"], unique=False)
    op.create_index("ix_assets_status", "assets", ["status"], unique=False)
    op.create_index("ix_assets_workspace_id", "assets", ["workspace_id"], unique=False)
    op.create_table(
        "brand_kits",
        sa.Column("brand_name", sa.String(), nullable=False),
        sa.Column("logo_url", sa.String(), nullable=True),
        sa.Column("primary_color", sa.String(length=7), nullable=True),
        sa.Column("secondary_color", sa.String(length=7), nullable=True),
        sa.Column("accent_color", sa.String(length=7), nullable=True),
        sa.Column("font_family", sa.String(length=100), nullable=True),
        sa.Column("brand_voice", sa.String(), nullable=True),
        sa.Column("tone_of_voice", sa.String(), nullable=True),
        sa.Column("brand_description", sa.Text(), nullable=True),
        sa.Column("website_url", sa.String(), nullable=True),
        sa.Column("industry", sa.String(), nullable=True),
        sa.Column("target_audience", sa.Text(), nullable=True),
        sa.Column("default_language", sa.String(length=10), nullable=True),
        sa.Column("ai_writing_instructions", sa.Text(), nullable=True),
        sa.Column("ai_content_restrictions", sa.Text(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_brand_kits_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_brand_kits_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_brand_kits_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_brand_kits")),
        sa.UniqueConstraint("workspace_id", name="uq_brand_kits_workspace_id"),
    )
    op.create_index(
        op.f("ix_brand_kits_deleted_at"), "brand_kits", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_brand_kits_id"), "brand_kits", ["id"], unique=False)
    op.create_index(
        op.f("ix_brand_kits_workspace_id"), "brand_kits", ["workspace_id"], unique=False
    )
    op.create_table(
        "campaigns",
        sa.Column("owner_id", sa.UUID(), nullable=False),
        sa.Column("brand_kit_id", sa.UUID(), nullable=True),
        sa.Column("campaign_name", sa.String(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("objective", sa.String(), nullable=True),
        sa.Column("campaign_type", sa.String(), nullable=True),
        sa.Column("target_channels", sa.String(), nullable=True),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("budget", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("currency", sa.String(length=3), nullable=True),
        sa.Column("start_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("end_date", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["brand_kit_id"],
            ["brand_kits.id"],
            name=op.f("fk_campaigns_brand_kit_id_brand_kits"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_campaigns_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
            name=op.f("fk_campaigns_owner_id_users"),
            ondelete="RESTRICT",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_campaigns_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaigns_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaigns")),
    )
    op.create_index(
        op.f("ix_campaigns_deleted_at"), "campaigns", ["deleted_at"], unique=False
    )
    op.create_index(op.f("ix_campaigns_id"), "campaigns", ["id"], unique=False)
    op.create_index("ix_campaigns_status", "campaigns", ["status"], unique=False)
    op.create_index(
        op.f("ix_campaigns_workspace_id"), "campaigns", ["workspace_id"], unique=False
    )
    op.create_index(
        "ix_campaigns_workspace_name",
        "campaigns",
        ["workspace_id", "campaign_name"],
        unique=True,
    )
    op.create_table(
        "campaign_assets",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_campaign_assets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_assets_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "campaign_id", "asset_id", name=op.f("pk_campaign_assets")
        ),
    )
    op.create_table(
        "campaign_content",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("content_type", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("language", sa.String(length=10), nullable=True),
        sa.Column("body", sa.Text(), nullable=True),
        sa.Column("summary", sa.Text(), nullable=True),
        sa.Column("hashtags", sa.String(), nullable=True),
        sa.Column("cta", sa.String(), nullable=True),
        sa.Column("seo_title", sa.String(), nullable=True),
        sa.Column("seo_description", sa.String(), nullable=True),
        sa.Column("version", sa.Integer(), nullable=False),
        sa.Column("parent_version_id", sa.UUID(), nullable=True),
        sa.Column("is_current", sa.Boolean(), nullable=False),
        sa.Column("scheduled_placeholder", sa.String(), nullable=True),
        sa.Column("metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_content_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_campaign_content_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["parent_version_id"],
            ["campaign_content.id"],
            name=op.f("fk_campaign_content_parent_version_id_campaign_content"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_campaign_content_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaign_content_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_content")),
    )
    op.create_index(
        "ix_campaign_content_campaign_id",
        "campaign_content",
        ["campaign_id"],
        unique=False,
    )
    op.create_index(
        "ix_campaign_content_content_type",
        "campaign_content",
        ["content_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_content_deleted_at"),
        "campaign_content",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_campaign_content_id"), "campaign_content", ["id"], unique=False
    )
    op.create_index(
        "ix_campaign_content_language", "campaign_content", ["language"], unique=False
    )
    op.create_index(
        "ix_campaign_content_status", "campaign_content", ["status"], unique=False
    )
    op.create_index(
        "ix_campaign_content_version", "campaign_content", ["version"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_content_workspace_id"),
        "campaign_content",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "campaign_schedules",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("publish_date", sa.DateTime(timezone=True), nullable=False),
        sa.Column("timezone", sa.String(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("error_message", sa.String(), nullable=True),
        sa.Column("retry_count", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_schedules_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_campaign_schedules_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_campaign_schedules_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaign_schedules_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_schedules")),
        sa.UniqueConstraint(
            "campaign_id", name=op.f("uq_campaign_schedules_campaign_id")
        ),
    )
    op.create_index(
        op.f("ix_campaign_schedules_id"), "campaign_schedules", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_schedules_workspace_id"),
        "campaign_schedules",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "campaign_content_assets",
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("asset_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["asset_id"],
            ["assets.id"],
            name=op.f("fk_campaign_content_assets_asset_id_assets"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["campaign_content.id"],
            name=op.f("fk_campaign_content_assets_content_id_campaign_content"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint(
            "content_id", "asset_id", name=op.f("pk_campaign_content_assets")
        ),
    )
    op.drop_column("users", "is_verified")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users",
        sa.Column(
            "is_verified",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
    )
    op.drop_table("campaign_content_assets")
    op.drop_index(
        op.f("ix_campaign_schedules_workspace_id"), table_name="campaign_schedules"
    )
    op.drop_index(op.f("ix_campaign_schedules_id"), table_name="campaign_schedules")
    op.drop_table("campaign_schedules")
    op.drop_index(
        op.f("ix_campaign_content_workspace_id"), table_name="campaign_content"
    )
    op.drop_index("ix_campaign_content_version", table_name="campaign_content")
    op.drop_index("ix_campaign_content_status", table_name="campaign_content")
    op.drop_index("ix_campaign_content_language", table_name="campaign_content")
    op.drop_index(op.f("ix_campaign_content_id"), table_name="campaign_content")
    op.drop_index(op.f("ix_campaign_content_deleted_at"), table_name="campaign_content")
    op.drop_index("ix_campaign_content_content_type", table_name="campaign_content")
    op.drop_index("ix_campaign_content_campaign_id", table_name="campaign_content")
    op.drop_table("campaign_content")
    op.drop_table("campaign_assets")
    op.drop_index("ix_campaigns_workspace_name", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_workspace_id"), table_name="campaigns")
    op.drop_index("ix_campaigns_status", table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_id"), table_name="campaigns")
    op.drop_index(op.f("ix_campaigns_deleted_at"), table_name="campaigns")
    op.drop_table("campaigns")
    op.drop_index(op.f("ix_brand_kits_workspace_id"), table_name="brand_kits")
    op.drop_index(op.f("ix_brand_kits_id"), table_name="brand_kits")
    op.drop_index(op.f("ix_brand_kits_deleted_at"), table_name="brand_kits")
    op.drop_table("brand_kits")
    op.drop_index("ix_assets_workspace_id", table_name="assets")
    op.drop_index("ix_assets_status", table_name="assets")
    op.drop_index(op.f("ix_assets_id"), table_name="assets")
    op.drop_index(op.f("ix_assets_deleted_at"), table_name="assets")
    op.drop_index("ix_assets_created_at", table_name="assets")
    op.drop_index("ix_assets_checksum", table_name="assets")
    op.drop_index("ix_assets_asset_type", table_name="assets")
    op.drop_table("assets")
    # ### end Alembic commands ###
