"""create_social_accounts_and_publishing

Revision ID: 7cd2bc4e2c0d
Revises: 6d964d031095
Create Date: 2026-07-31 12:59:22.366487

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "7cd2bc4e2c0d"
down_revision: Union[str, Sequence[str], None] = "6d964d031095"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "social_accounts",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_social_accounts_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_social_accounts_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_social_accounts_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_social_accounts")),
    )
    op.create_index(
        "ix_social_accounts_account_id", "social_accounts", ["account_id"], unique=False
    )
    op.create_index(
        op.f("ix_social_accounts_deleted_at"),
        "social_accounts",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_social_accounts_id"), "social_accounts", ["id"], unique=False
    )
    op.create_index(
        "ix_social_accounts_provider", "social_accounts", ["provider"], unique=False
    )
    op.create_index(
        op.f("ix_social_accounts_workspace_id"),
        "social_accounts",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "publish_history",
        sa.Column("campaign_id", sa.UUID(), nullable=True),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("social_account_id", sa.UUID(), nullable=False),
        sa.Column("status", sa.String(), nullable=False),
        sa.Column("external_post_id", sa.String(), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("created_by", sa.UUID(), nullable=True),
        sa.Column("updated_by", sa.UUID(), nullable=True),
        sa.Column("deleted_at", sa.DateTime(), nullable=True),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_publish_history_campaign_id_campaigns"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["campaign_content.id"],
            name=op.f("fk_publish_history_content_id_campaign_content"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_publish_history_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["social_account_id"],
            ["social_accounts.id"],
            name=op.f("fk_publish_history_social_account_id_social_accounts"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["updated_by"],
            ["users.id"],
            name=op.f("fk_publish_history_updated_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_publish_history_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_publish_history")),
    )
    op.create_index(
        "ix_publish_history_content_id", "publish_history", ["content_id"], unique=False
    )
    op.create_index(
        op.f("ix_publish_history_deleted_at"),
        "publish_history",
        ["deleted_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_publish_history_id"), "publish_history", ["id"], unique=False
    )
    op.create_index(
        "ix_publish_history_status", "publish_history", ["status"], unique=False
    )
    op.create_index(
        op.f("ix_publish_history_workspace_id"),
        "publish_history",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_publish_history_workspace_id"), table_name="publish_history")
    op.drop_index("ix_publish_history_status", table_name="publish_history")
    op.drop_index(op.f("ix_publish_history_id"), table_name="publish_history")
    op.drop_index(op.f("ix_publish_history_deleted_at"), table_name="publish_history")
    op.drop_index("ix_publish_history_content_id", table_name="publish_history")
    op.drop_table("publish_history")
    op.drop_index(op.f("ix_social_accounts_workspace_id"), table_name="social_accounts")
    op.drop_index("ix_social_accounts_provider", table_name="social_accounts")
    op.drop_index(op.f("ix_social_accounts_id"), table_name="social_accounts")
    op.drop_index(op.f("ix_social_accounts_deleted_at"), table_name="social_accounts")
    op.drop_index("ix_social_accounts_account_id", table_name="social_accounts")
    op.drop_table("social_accounts")
    # ### end Alembic commands ###
