"""create_job_execution_model

Revision ID: 83b54929f8a9
Revises: a7be752e9027
Create Date: 2026-07-31 14:42:54.022242

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "83b54929f8a9"
down_revision: Union[str, Sequence[str], None] = "a7be752e9027"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "job_executions",
        sa.Column("job_name", sa.String(), nullable=False),
        sa.Column("queue", sa.String(), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "QUEUED",
                "RUNNING",
                "RETRYING",
                "COMPLETED",
                "FAILED",
                "CANCELLED",
                name="jobstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "priority",
            sa.Enum("LOW", "DEFAULT", "HIGH", "CRITICAL", name="jobpriority"),
            nullable=False,
        ),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("max_attempts", sa.Integer(), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("failed_at", sa.DateTime(), nullable=True),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_executions")),
    )
    op.create_index(
        op.f("ix_job_executions_id"), "job_executions", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_job_executions_job_name"), "job_executions", ["job_name"], unique=False
    )
    op.create_index(
        op.f("ix_job_executions_priority"), "job_executions", ["priority"], unique=False
    )
    op.create_index(
        op.f("ix_job_executions_queue"), "job_executions", ["queue"], unique=False
    )
    op.create_index(
        op.f("ix_job_executions_status"), "job_executions", ["status"], unique=False
    )
    op.create_index(
        "ix_job_executions_status_queue",
        "job_executions",
        ["status", "queue"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_job_executions_status_queue", table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_status"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_queue"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_priority"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_job_name"), table_name="job_executions")
    op.drop_index(op.f("ix_job_executions_id"), table_name="job_executions")
    op.drop_table("job_executions")
    # ### end Alembic commands ###
