"""create_platform_ops_models

Revision ID: 8a832dfa39d0
Revises: 8c6ab8f9e25e
Create Date: 2026-07-31 15:12:44.165042

"""

from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8a832dfa39d0"
down_revision: Union[str, Sequence[str], None] = "8c6ab8f9e25e"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "feature_flags",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_feature_flags")),
    )
    op.create_index(op.f("ix_feature_flags_key"), "feature_flags", ["key"], unique=True)
    op.create_table(
        "runtime_configurations",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("key", sa.String(), nullable=False),
        sa.Column("value", sa.String(), nullable=False),
        sa.Column(
            "data_type",
            sa.Enum("STRING", "INTEGER", "BOOLEAN", "FLOAT", "JSON", name="datatype"),
            nullable=False,
        ),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_runtime_configurations")),
    )
    op.create_index(
        op.f("ix_runtime_configurations_key"),
        "runtime_configurations",
        ["key"],
        unique=True,
    )
    op.create_table(
        "system_announcements",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(), nullable=False),
        sa.Column("message", sa.String(), nullable=False),
        sa.Column("type", sa.String(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("dismissible", sa.Boolean(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_system_announcements")),
    )
    op.create_table(
        "workspace_features",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.Column("flag_key", sa.String(), nullable=False),
        sa.Column("is_enabled", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_workspace_features_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_workspace_features")),
    )
    op.create_index(
        op.f("ix_workspace_features_flag_key"),
        "workspace_features",
        ["flag_key"],
        unique=False,
    )
    op.create_index(
        op.f("ix_workspace_features_workspace_id"),
        "workspace_features",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_workspace_features_workspace_id"), table_name="workspace_features"
    )
    op.drop_index(
        op.f("ix_workspace_features_flag_key"), table_name="workspace_features"
    )
    op.drop_table("workspace_features")
    op.drop_table("system_announcements")
    op.drop_index(
        op.f("ix_runtime_configurations_key"), table_name="runtime_configurations"
    )
    op.drop_table("runtime_configurations")
    op.drop_index(op.f("ix_feature_flags_key"), table_name="feature_flags")
    op.drop_table("feature_flags")
    # ### end Alembic commands ###
