"""update_audit_log_model

Revision ID: 8c6ab8f9e25e
Revises: 83b54929f8a9
Create Date: 2026-07-31 15:06:36.138849

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "8c6ab8f9e25e"
down_revision: Union[str, Sequence[str], None] = "83b54929f8a9"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("audit_logs", sa.Column("actor_id", sa.UUID(), nullable=True))
    op.add_column("audit_logs", sa.Column("resource_type", sa.String(), nullable=False))
    op.add_column("audit_logs", sa.Column("user_agent", sa.String(), nullable=True))
    op.add_column("audit_logs", sa.Column("correlation_id", sa.String(), nullable=True))
    op.add_column(
        "audit_logs",
        sa.Column(
            "timestamp", sa.DateTime(), server_default=sa.text("now()"), nullable=False
        ),
    )
    op.alter_column(
        "audit_logs", "workspace_id", existing_type=sa.UUID(), nullable=True
    )
    op.alter_column(
        "audit_logs", "resource_id", existing_type=sa.VARCHAR(), nullable=False
    )
    op.drop_index(op.f("ix_audit_logs_action"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_request_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_user_id"), table_name="audit_logs")
    op.create_index(
        op.f("ix_audit_logs_actor_id"), "audit_logs", ["actor_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_correlation_id"),
        "audit_logs",
        ["correlation_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_resource_type"),
        "audit_logs",
        ["resource_type"],
        unique=False,
    )
    op.create_index(
        op.f("ix_audit_logs_timestamp"), "audit_logs", ["timestamp"], unique=False
    )
    op.create_index(
        "ix_audit_logs_workspace_resource",
        "audit_logs",
        ["workspace_id", "resource_type"],
        unique=False,
    )
    op.drop_constraint(
        op.f("fk_audit_logs_workspace_id_workspaces"), "audit_logs", type_="foreignkey"
    )
    op.drop_constraint(
        op.f("fk_audit_logs_user_id_users"), "audit_logs", type_="foreignkey"
    )
    op.drop_column("audit_logs", "created_at")
    op.drop_column("audit_logs", "resource")
    op.drop_column("audit_logs", "user_id")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "audit_logs",
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=True),
    )
    op.add_column(
        "audit_logs",
        sa.Column("resource", sa.VARCHAR(), autoincrement=False, nullable=False),
    )
    op.add_column(
        "audit_logs",
        sa.Column(
            "created_at", postgresql.TIMESTAMP(), autoincrement=False, nullable=False
        ),
    )
    op.create_foreign_key(
        op.f("fk_audit_logs_user_id_users"),
        "audit_logs",
        "users",
        ["user_id"],
        ["id"],
        ondelete="SET NULL",
    )
    op.create_foreign_key(
        op.f("fk_audit_logs_workspace_id_workspaces"),
        "audit_logs",
        "workspaces",
        ["workspace_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.drop_index("ix_audit_logs_workspace_resource", table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_timestamp"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_resource_type"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_correlation_id"), table_name="audit_logs")
    op.drop_index(op.f("ix_audit_logs_actor_id"), table_name="audit_logs")
    op.create_index(
        op.f("ix_audit_logs_user_id"), "audit_logs", ["user_id"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_resource"), "audit_logs", ["resource"], unique=False
    )
    op.create_index(
        op.f("ix_audit_logs_request_id"), "audit_logs", ["request_id"], unique=False
    )
    op.create_index(op.f("ix_audit_logs_id"), "audit_logs", ["id"], unique=False)
    op.create_index(
        op.f("ix_audit_logs_action"), "audit_logs", ["action"], unique=False
    )
    op.alter_column(
        "audit_logs", "resource_id", existing_type=sa.VARCHAR(), nullable=True
    )
    op.alter_column(
        "audit_logs", "workspace_id", existing_type=sa.UUID(), nullable=False
    )
    op.drop_column("audit_logs", "timestamp")
    op.drop_column("audit_logs", "correlation_id")
    op.drop_column("audit_logs", "user_agent")
    op.drop_column("audit_logs", "resource_type")
    op.drop_column("audit_logs", "actor_id")
    # ### end Alembic commands ###
