"""create_analytics_foundation

Revision ID: e0e714307b3a
Revises: 7cd2bc4e2c0d
Create Date: 2026-07-31 14:05:57.481508

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e0e714307b3a"
down_revision: Union[str, Sequence[str], None] = "7cd2bc4e2c0d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ai_usage",
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("model", sa.String(), nullable=False),
        sa.Column("generations", sa.Integer(), nullable=False),
        sa.Column("success_count", sa.Integer(), nullable=False),
        sa.Column("failure_count", sa.Integer(), nullable=False),
        sa.Column("total_tokens", sa.Integer(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_ai_usage_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_ai_usage")),
    )
    op.create_index(op.f("ix_ai_usage_id"), "ai_usage", ["id"], unique=False)
    op.create_index("ix_ai_usage_provider", "ai_usage", ["provider"], unique=False)
    op.create_index(
        op.f("ix_ai_usage_workspace_id"), "ai_usage", ["workspace_id"], unique=False
    )
    op.create_table(
        "analytics_snapshots",
        sa.Column("snapshot_type", sa.String(), nullable=False),
        sa.Column("snapshot_date", sa.Date(), nullable=False),
        sa.Column(
            "campaign_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("ai_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "publishing_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column(
            "workspace_metrics", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_analytics_snapshots_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_analytics_snapshots")),
    )
    op.create_index(
        op.f("ix_analytics_snapshots_id"), "analytics_snapshots", ["id"], unique=False
    )
    op.create_index(
        "ix_analytics_snapshots_type_date",
        "analytics_snapshots",
        ["workspace_id", "snapshot_type", "snapshot_date"],
        unique=True,
    )
    op.create_index(
        op.f("ix_analytics_snapshots_workspace_id"),
        "analytics_snapshots",
        ["workspace_id"],
        unique=False,
    )
    op.create_table(
        "campaign_analytics",
        sa.Column("campaign_id", sa.UUID(), nullable=False),
        sa.Column("impressions", sa.Integer(), nullable=False),
        sa.Column("reach", sa.Integer(), nullable=False),
        sa.Column("clicks", sa.Integer(), nullable=False),
        sa.Column("likes", sa.Integer(), nullable=False),
        sa.Column("comments", sa.Integer(), nullable=False),
        sa.Column("shares", sa.Integer(), nullable=False),
        sa.Column("saves", sa.Integer(), nullable=False),
        sa.Column("engagement_rate", sa.Float(), nullable=False),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.Column("workspace_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(
            ["campaign_id"],
            ["campaigns.id"],
            name=op.f("fk_campaign_analytics_campaign_id_campaigns"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["workspace_id"],
            ["workspaces.id"],
            name=op.f("fk_campaign_analytics_workspace_id_workspaces"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_campaign_analytics")),
        sa.UniqueConstraint(
            "campaign_id", name=op.f("uq_campaign_analytics_campaign_id")
        ),
    )
    op.create_index(
        op.f("ix_campaign_analytics_id"), "campaign_analytics", ["id"], unique=False
    )
    op.create_index(
        op.f("ix_campaign_analytics_workspace_id"),
        "campaign_analytics",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_campaign_analytics_workspace_id"), table_name="campaign_analytics"
    )
    op.drop_index(op.f("ix_campaign_analytics_id"), table_name="campaign_analytics")
    op.drop_table("campaign_analytics")
    op.drop_index(
        op.f("ix_analytics_snapshots_workspace_id"), table_name="analytics_snapshots"
    )
    op.drop_index("ix_analytics_snapshots_type_date", table_name="analytics_snapshots")
    op.drop_index(op.f("ix_analytics_snapshots_id"), table_name="analytics_snapshots")
    op.drop_table("analytics_snapshots")
    op.drop_index(op.f("ix_ai_usage_workspace_id"), table_name="ai_usage")
    op.drop_index("ix_ai_usage_provider", table_name="ai_usage")
    op.drop_index(op.f("ix_ai_usage_id"), table_name="ai_usage")
    op.drop_table("ai_usage")
    # ### end Alembic commands ###
