"""create_integration_connection

Revision ID: f89bcb79da50
Revises: 8a832dfa39d0
Create Date: 2026-07-31 15:34:38.558843

"""

from typing import Sequence, Union

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "f89bcb79da50"
down_revision: Union[str, Sequence[str], None] = "8a832dfa39d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "integration_connections",
        sa.Column("workspace_id", sa.Uuid(), nullable=False),
        sa.Column("provider", sa.String(length=50), nullable=False),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "CONNECTED",
                "DISCONNECTED",
                "ERROR",
                "EXPIRED",
                name="connectionstatus",
            ),
            nullable=False,
        ),
        sa.Column("access_token", sa.Text(), nullable=True),
        sa.Column("refresh_token", sa.Text(), nullable=True),
        sa.Column("expires_at", sa.DateTime(), nullable=True),
        sa.Column(
            "metadata_info", postgresql.JSONB(astext_type=sa.Text()), nullable=True
        ),
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_integration_connections")),
    )
    op.create_index(
        op.f("ix_integration_connections_id"),
        "integration_connections",
        ["id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_provider"),
        "integration_connections",
        ["provider"],
        unique=False,
    )
    op.create_index(
        op.f("ix_integration_connections_workspace_id"),
        "integration_connections",
        ["workspace_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_integration_connections_workspace_id"),
        table_name="integration_connections",
    )
    op.drop_index(
        op.f("ix_integration_connections_provider"),
        table_name="integration_connections",
    )
    op.drop_index(
        op.f("ix_integration_connections_id"), table_name="integration_connections"
    )
    op.drop_table("integration_connections")
    # ### end Alembic commands ###
