import uuid
from typing import Sequence
from sqlalchemy.ext.asyncio import AsyncSession
from sqlalchemy import select, and_, desc, update
from sqlalchemy.orm import selectinload
from app.repositories.base import BaseRepository
from app.models.campaign_content import CampaignContent
from app.constants.enums import ContentStatus
from datetime import datetime, timezone

class CampaignContentRepository(BaseRepository[CampaignContent]):
    async def get_current_version(self, db: AsyncSession, workspace_id: uuid.UUID, campaign_id: uuid.UUID, content_id: uuid.UUID) -> CampaignContent | None:
        stmt = select(self.model).where(
            self.model.id == content_id,
            self.model.campaign_id == campaign_id,
            self.model.workspace_id == workspace_id,
            self.model.is_current == True,
            self.model.deleted_at.is_(None)
        ).options(
            selectinload(self.model.assets)
        )
        result = await db.execute(stmt)
        return result.scalar_one_or_none()

    async def list_by_campaign(self, db: AsyncSession, workspace_id: uuid.UUID, campaign_id: uuid.UUID, limit: int = 100, offset: int = 0) -> Sequence[CampaignContent]:
        stmt = select(self.model).where(
            self.model.campaign_id == campaign_id,
            self.model.workspace_id == workspace_id,
            self.model.is_current == True,
            self.model.deleted_at.is_(None)
        ).options(
            selectinload(self.model.assets)
        ).order_by(desc(self.model.created_at)).limit(limit).offset(offset)
        result = await db.execute(stmt)
        return result.scalars().all()

    async def list_versions(self, db: AsyncSession, workspace_id: uuid.UUID, content_id: uuid.UUID) -> Sequence[CampaignContent]:
        # To list versions, we need to find the root parent (which could be the first one created)
        # However, for simplicity, we can assume parent_version_id chaining or all sharing a lineage group.
        # A more robust way is querying by ID or parent_version_id recursively, but let's query where ID matches or parent matches (shallow versioning for now as per requirements)
        # Let's find the content first to see its lineage
        base = await self.get(db, content_id)
        if not base:
            return []
        
        # If we just want simple versioning, we can trace by searching for all items that share the same origin.
        # To avoid complex CTEs in this phase, we will assume versions are generated by taking the current and making a new one with parent_version_id.
        # A simple tree walk or we can just fetch all content where parent_version_id is the original content's ID, plus the original content.
        # For full lineage, we might need a `lineage_id` in the future. For now, we will query all where parent_version_id == content_id OR id == content_id
        
        # Actually, let's just implement a simple single-level parent-child for this phase.
        # Real versioning usually involves a `group_id`. Let's assume the user queries the original content ID.
        stmt = select(self.model).where(
            self.model.workspace_id == workspace_id,
            # Either it's the root or a child of the root
            (self.model.id == content_id) | (self.model.parent_version_id == content_id)
        ).order_by(desc(self.model.version))
        result = await db.execute(stmt)
        return result.scalars().all()

    async def create_version(self, db: AsyncSession, base_content: CampaignContent) -> CampaignContent:
        # Create a new version
        new_version_data = {
            "campaign_id": base_content.campaign_id,
            "workspace_id": base_content.workspace_id,
            "title": base_content.title,
            "content_type": base_content.content_type,
            "status": base_content.status,
            "language": base_content.language,
            "body": base_content.body,
            "summary": base_content.summary,
            "hashtags": base_content.hashtags,
            "cta": base_content.cta,
            "seo_title": base_content.seo_title,
            "seo_description": base_content.seo_description,
            "version": base_content.version + 1,
            "parent_version_id": base_content.id if not base_content.parent_version_id else base_content.parent_version_id,
            "is_current": True,
            "metadata_": base_content.metadata_,
            "created_by": base_content.created_by,
            "updated_by": base_content.updated_by
        }
        
        # Unset is_current on old version
        base_content.is_current = False
        db.add(base_content)
        
        new_content = self.model(**new_version_data)
        db.add(new_content)
        await db.flush()
        
        # Copy assets
        if base_content.assets:
            new_content.assets = list(base_content.assets)
            db.add(new_content)
            await db.flush()
            
        return new_content

    async def restore_version(self, db: AsyncSession, workspace_id: uuid.UUID, campaign_id: uuid.UUID, version_id_to_restore: uuid.UUID) -> CampaignContent | None:
        # Get the version to restore
        stmt = select(self.model).where(
            self.model.id == version_id_to_restore,
            self.model.workspace_id == workspace_id,
            self.model.campaign_id == campaign_id
        )
        result = await db.execute(stmt)
        target = result.scalar_one_or_none()
        
        if not target:
            return None
            
        # Find the currently active version in this lineage
        lineage_id = target.parent_version_id or target.id
        
        # Set all in lineage to not current
        update_stmt = update(self.model).where(
            self.model.workspace_id == workspace_id,
            self.model.campaign_id == campaign_id,
            (self.model.id == lineage_id) | (self.model.parent_version_id == lineage_id)
        ).values(is_current=False)
        await db.execute(update_stmt)
        
        # Set the target to current
        target.is_current = True
        db.add(target)
        await db.flush()
        
        return target

    async def soft_delete(self, db: AsyncSession, content: CampaignContent) -> bool:
        content.deleted_at = datetime.now(timezone.utc)
        content.is_current = False
        db.add(content)
        await db.flush()
        return True

campaign_content_repo = CampaignContentRepository(CampaignContent)
